"""
Query collectors for SQL Batcher.

This module contains query collector implementations for SQL Batcher.
Query collectors are used to collect and analyze SQL queries generated by the batcher.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Union


class QueryCollector(ABC):
    """
    Abstract base class for query collectors.

    Query collectors are used to collect and analyze SQL queries generated
    by SQL Batcher. This is particularly useful in dry run mode to analyze
    the batches that would be executed without actually executing them.
    """

    @abstractmethod
    def collect(self, query: str, metadata: Optional[Dict[str, Any]] = None) -> None:
        """
        Collect a query.

        Args:
            query: SQL query to collect
            metadata: Optional metadata to associate with the query
        """
        pass

    @abstractmethod
    def get_queries(self) -> List[Dict[str, Any]]:
        """
        Get all collected queries.

        Returns:
            List of collected queries
        """
        pass

    @abstractmethod
    def clear(self) -> None:
        """Clear all collected queries."""
        pass


class ListQueryCollector(QueryCollector):
    """
    Simple in-memory query collector that stores queries in a list.

    This collector stores each query in a list with its associated metadata.
    It's useful for simple analysis and debugging.
    """

    def __init__(self):
        """Initialize the list query collector."""
        self.queries: List[Dict[str, Any]] = []

    def collect(self, query: str, metadata: Optional[Dict[str, Any]] = None) -> None:
        """
        Collect a query.

        Args:
            query: SQL query to collect
            metadata: Optional metadata to associate with the query
        """
        self.queries.append({"query": query, "metadata": metadata or {}})

    def get_queries(self) -> List[Dict[str, Any]]:
        """
        Get all collected queries.

        Returns:
            List of collected queries
        """
        return self.queries

    def clear(self) -> None:
        """Clear all collected queries."""
        self.queries = []
